@url = http://localhost:4000/api/solicitudes

### --Mostrar todas las solicitudes--

GET {{url}}

### --Crear nueva solicitud--

POST {{url}}
Content-Type: application/json

{
    "Radicado": "mvmprueba-1",
    "Descripcion": "Solicitud 1",
    "CorreoSolicitante": "correo1@prueba.com",
    "NombreSolicitante": "Prueba1",
    "ApellidoSolicitante": "Solicitud1",
    "TelefonoSolicitante": "3141234567",
    "NombreEmpresa": "NOVATECH",
    "IdTipoSolicitud": 1,
    "IDEstado": 1
}

### --Mostrar una solicitud según el id--

GET {{url}}/68

### --Eliminar una solicitud según el id--

DELETE {{url}}/71

### --Actualizar responsable y estado según id--

PUT {{url}}/72
Content-Type: application/json

{
    "IDResponsable": 4
}
