@url = http://localhost:4000/api

### --Mostrar todas las solicitudes--

GET {{url}}/solicitudes

### --Crear nueva solicitud--

POST {{url}}/solicitudes
Content-Type: application/json

{
    "Descripcion": "Solicitud 10",
    "CorreoSolicitante": "correo10@prueba.com",
    "NombreSolicitante": "Prueba10",
    "ApellidoSolicitante": "Solicitud10",
    "TelefonoSolicitante": "3141234568",
    "NombreEmpresa": "NOVATECH",
    "IdTipoSolicitud": 1
}

### --Mostrar una solicitud según el id--

GET {{url}}/solicitudes/68

### --Eliminar una solicitud según el id--

DELETE {{url}}/solicitudes/71

### --Actualizar responsable y estado según id--

PUT {{url}}/solicitudes/72
Content-Type: application/json

{
    "IDResponsable": 1
}

### --Obtener tipos de solicitud--
GET {{url}}/tipoSolicitud